debian/lib/python: Ahem, fix FTBFS
AttributeError: 'VersionXen' object has no attribute 'xen_version'

Since it's already in the master branch, we can't fix it up, whoops.